import { db } from "./../firebaseConfig";

const editPaciente = ({
  id,
  nombreYApellido,
  fechaDeNacimiento,
  edad,
  ciudad,
  telefono,
  correo,
  hijos,
  conQuienVive,
  motivoConsulta,
  enfCardiacas,
  diabetes,
  presionAlta,
  asma,
  alergias,
  hipoHiperTiroidismo,
  sindromeOvarioPoliquistico,
  intoleranciaLactosa,
  celiaquia,
  gastritis,
  estreñimiento,
  cicloMenstrual,
  otros,
  intervencionesQuirurjicas,
  medicacion,
  suplementos,
  molestias,
  fuma,
  bebidasAlcoholicas,
  alergiasAlimentarias,
  alimentosQueNoLeGustan,
  preferencia,
  rutinaActividadDiaria,
  trabajaEstudia,
  horarioRutina,
  horaDespertar,
  cantidadComidasAlDia,
  dondeCome,
  conQuienCome,
  responsableComidas,
  compra,
  comeEntreHoras,
  actividadFisica,
  desayuno,
  colacion,
  almuerzo,
  merienda,
  cena,
}) => {
  return db.collection("pacientes").doc(id).update({
    nombreYApellido: nombreYApellido,
    fechaDeNacimiento: fechaDeNacimiento,
    edad: edad,
    ciudad: ciudad,
    telefono: telefono,
    correo: correo,
    hijos: hijos,
    conQuienVive: conQuienVive,
    motivoConsulta: motivoConsulta,
    enfCardiacas: enfCardiacas,
    diabetes: diabetes,
    presionAlta: presionAlta,
    asma: asma,
    alergias: alergias,
    hipoHiperTiroidismo: hipoHiperTiroidismo,
    sindromeOvarioPoliquistico: sindromeOvarioPoliquistico,
    intoleranciaLactosa: intoleranciaLactosa,
    celiaquia: celiaquia,
    gastritis: gastritis,
    estreñimiento: estreñimiento,
    cicloMenstrual: cicloMenstrual,
    otros: otros,
    intervencionesQuirurjicas: intervencionesQuirurjicas,
    medicacion: medicacion,
    suplementos: suplementos,
    molestias: molestias,
    fuma: fuma,
    bebidasAlcoholicas: bebidasAlcoholicas,
    alergiasAlimentarias: alergiasAlimentarias,
    alimentosQueNoLeGustan: alimentosQueNoLeGustan,
    preferencia: preferencia,
    rutinaActividadDiaria: rutinaActividadDiaria,
    trabajaEstudia: trabajaEstudia,
    horarioRutina: horarioRutina,
    horaDespertar: horaDespertar,
    cantidadComidasAlDia: cantidadComidasAlDia,
    dondeCome: dondeCome,
    conQuienCome: conQuienCome,
    responsableComidas: responsableComidas,
    compra: compra,
    comeEntreHoras: comeEntreHoras,
    actividadFisica: actividadFisica,
    desayuno: desayuno,
    colacion: colacion,
    almuerzo: almuerzo,
    merienda: merienda,
    cena: cena,
  });
};

export default editPaciente;
